version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci:"
    target-branch: "main"
    groups:
      "github-actions":
        patterns:
          - "*"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build:"
    target-branch: "main"
    groups:
      "database":
        patterns:
          - "org.flywaydb*"
          - "org.jooq*"
          - "com.h2database*"
          - "org.xerial*"
          - "com.mysql*"
          - "org.mariadb.jdbc*"
          - "redis.clients*"
          - "io.nats:jnats*"
          - "com.rabbitmq*"
      "testing":
        patterns:
          - "org.junit*"
          - "org.testcontainers*"
      "milkdrinkers":
        patterns:
          - "io.github.milkdrinkers*"
      "net.kyori":
        patterns:
          - "net.kyori*"
