# Database Settings
database:
  # Available types: "sqlite", "h2", "mysql", "mariadb"
  type: "sqlite"
  table-prefix: "example_"

  # Authentication
  host: "localhost"
  port: 3306
  database: "database_name"
  username: "root"
  password: ""

  # Advanced settings (Please don't touch unless you know what you're doing!)
  advanced:
    # Should we try to repair broken migrations to the database
    repair: false

    # Configure the HikariCP connection pool
    connection-pool:
      max-pool-size: 10
      min-idle: 10
      max-lifetime: 180000
      keepalive-time: 60000
      connection-timeout: 20000

    # A list of connection parameters, you can include more by adding them on a new line
    connection-properties:
      useSSL: false
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false

# Message Broker Settings
messaging:
  # Enable or disable the message broker
  # This is only required if you are running the plugin on a server network
  enabled: true

  # How often to poll for new messages (in milliseconds)
  # Must be less than cleanup-interval, ideally 1/3 or less
  polling-interval: 1000

  # How often to clean up old messages (in milliseconds)
  # Must be at least 3x the polling-interval
  cleanup-interval: 30000

  # Available broker types: "sql", "plugin", "redis", "rabbitmq", "nats"
  type: "sql"

  # Connection settings (redis, rabbitmq, nats)
  address: "localhost:6379" # Can be a single entry, or a list of addresses if you wish to connect to a cluster
  username: ""
  password: ""

  # Advanced broker configuration
  advanced:
    # Authentication method: "password", "certificate", "token"
    auth-method: "password"

    # Token authentication (JWT, API keys, Redis AUTH tokens)
    auth-token: ""

    # SSL/TLS configuration
    ssl:
      enabled: false
      cert-path: ""              # Client certificate (.crt, .pem)
      key-path: ""               # Private key (.key, .pem)
      ca-path: ""                # Certificate Authority (.crt, .pem)
      verify-server-cert: true
      verify-hostname: true

    # RabbitMQ-specific settings
    rabbitmq:
      virtual-host: "/"

    # NATS-specific settings
    nats:
      nkey-seed-path: "" # NKey seed file for cryptographic auth
      jwt-file-path: "" # JWT token file
      credentials-path: "" # Combined JWT + NKey credentials file
